language: node_js
node_js:
- stable
before_install:
- npm install -g gulp
install:
- npm install
script:
- npm run build
after_success:
- npm run deploy
env:
  global:
    secure: k3TnLAHKbRMvCYqEUJZiTJyTvp824yUvC6DBa8V8ckBcEoEBbnKXJUVyX9kU5XmdzRk6j+6IeJb/YnI21U/uQUpexPtCvnJhDUJ2s3T4Q/2JzyA3dYVeEFZv/8zSraU11m2vU+DWUckklbnInMiJdO92XXYhoPMT6xZ/U2xl0oqmdzarNUfhFMTMU7xyMmkLnslrviSTb4atR/WYe05VZ8of1ziAyctFzAU/XUNzdjXAb8jnEdpFNMBoCZGsfmTmUrQck3d7Xth4fTVeaYgD9c5ZHkc3l3FUST1BUP/1qGiZVJ1C4DOW9gA7JPo3jHm4EcGBmy8KKDWa4aZi7EabinqA/7rd3X+CjQ6axSnRp7UUUcUVZHNaSI2v9xgccP0NvpmHRqKHquBlCW6J3wXkpFLf8a3ZW33wCREIwZVu79IzbsTi/GdXoTASoh7cUXyCmjDnpZYQjKREXgFAXEbfQ+dPWl1RZ8NP/cZKl1TYaG/G2OnKhCBTYWK5MZ6kdRB/kLp8nXsEDbH7HMYlFprMw8g4OhLNJa2Dlxdo6zxOkQy/fsTi8d3aX37eWD/opQ+5E56afckKJW0gGbOUok1dZIdBcwvdgMuStQ0tmuq7cDuvXq64LRBTNcjPTrXUY2ACriQkc/HykCVzfpWZmjxjoX53dqrJlKoTg4NX1dsUc3M=
